name: notify-slack
on:
  workflow_dispatch:
    inputs:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "check version"
        run: gh --version
